### ISSUE TITLE
IntelliGraph objects cannot be accessed using GtObjectPaths in the Python Module

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#192]
There seems to be a problem for GtObjectPath propeties if the name of the package object of the module ("IntelliGraphs") is not identical to the Module ID ("IntelliGraph").

Python process elements are writing some warnings to the log:   
INFO  [10:15:16] [Python Module (Python 3.9)] obj not found - path = IntelliGraph

**Comment by mariusalexander** [comment]
@jensschmeink I think this is more of an issue of GTlab's ` GtObjectPath`  properties or the process executor (or python)? 

We had a similar issue where a package could not be saved if the module id differs from the package's object name (see [gtlab-core/issues/153](https://github.com/dlr-gtlab/gtlab-core/issues/153) . We chose to allow package names that differ, therefore I would not suggest to rename the package of intelli graph nor rename the module-id but to search and fix the error in GTlab.

**Comment by rainman110** [comment]
@jensschmeink  + @marvinoe21  Could this be related to the problem that we just experienced, i.e. https://github.com/dlr-gtlab/python-module/issues/566

**Comment by jensschmeink** [comment]
> @jensschmeink + @marvinoe21 Could this be related to the problem that we just experienced, i.e. [dlr-gtlab/python-module#566](https://github.com/dlr-gtlab/python-module/issues/566)

Yes, I think so

**Comment by mariusalexander** [comment]
@jensschmeink May you check if the issue still persists?

**Comment by jensschmeink** [comment]
Problem seems to be solved with latest updates in python module
