### ISSUE TITLE
Intelligraph View does not autoamtically update / redraw on Linux

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/intelligraph-module#202]
On linux, the graphs seem to hang when auto-computation is enabled.

In fact it does not hang, but the view is just not redrawn.

To reproduce:
 - create a mini-graph e.g. using a bool input and bool display
 - Just toggle the input box, DONT MOVE THE MOUSE!

The view updates not until I move the mouse.

See this video as an example:

https://github.com/user-attachments/assets/e997b1ac-85d6-4589-9187-aa2f0a4869d0

**Comment by rainman110** [comment]
When looking at the double input example, the input box is updated to the "running" state, but no update  / redraw follows. 

Could it be, that the nodes need to inform the view to repaint?

**Comment by rainman110** [comment]
It seems to be fixed with the current master! Thanks :)

**Comment by mariusalexander** [comment]
I'll have to create a new release soon I think. The last release is quite old and contains a few bugs that have been fixed already.
