### ISSUE TITLE
Currently can not add intelligraph to exsisting project

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#204]

**Comment by rainman110** [comment]
I recently experienced the same problem, but only on linux.

**Comment by jensschmeink** [comment]
Seems to be related to the intelli folder in the project

**Comment by rainman110** [comment]
I am wondering, whether this happens only with gtlab 2.1, as the package interface has changed and was adapted.

**Comment by mariusalexander** [comment]
This is the same issue as described in #193 and it should already be fixed in the the main branch. Can you verify that you are not working on an outdated version?

**Comment by rainman110** [comment]
It's definitely possible that I used an outdated version. The problem is now gone.
