### ISSUE TITLE
Consider hiding size and position properties of nodes in dev mode as well

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#205]
Position and size of nodes have no value for the user and therefore should be hidden.

**Comment by mariusalexander** [comment]
The size and position properties are hidden if one does not use the `dev` mode of GTlab. Only the Node-Id is still displayed (see #79)

**Comment by jensschmeink** [comment]
Ok. I used it in dev mode so I was not aware of this. Is it interesting for the developer to see this values? I do not need them and so it could be hidden in dev mode aswell.

**Comment by mariusalexander** [comment]
I am not using them on a regular basis. The Node-Id should definitely be visible in `dev` mode as I use it regularly (it would be nice to see the uuid in `dev` mode as well on a side note), but I agree the size and position properties may be very well hidden in `dev` mode as well. I'll might add an compile flag one could set at compile time to display them though.

**Comment by mariusalexander** [comment]
Closes by #220
