### ISSUE TITLE
Crash while grouping nodes with auto evaluation enabled 

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#210]
I have a setup with a node which build a subgraph node in my main graph. If I copy the sub-graph-node from the main graph and try to insert in another graph GTlab crashes. 
If I pick the node in the subgraph it works

**Comment by jensschmeink** [comment]
Currently it even seems to be broken to join to nodes to a subgraph. This leads to a crahs in my test project :(

**Comment by rainman110** [comment]
It seems to be related to the auto-run feature. It only happens, if auto-run is enabled while grouping the nodes.

**Comment by rainman110** [comment]
Might be related to #203

**Comment by mariusalexander** [comment]
@jensschmeink Can you give a more detailed explanation of the steps you took so that I can try to reproduce the error on my side?

**Comment by jensschmeink** [comment]
> @jensschmeink Can you give a more detailed explanation of the steps you took so that I can try to reproduce the error on my side?

Go to a graph which is set to "automatic execution". Then select a node an put it in a sub-graph-> crash

**Comment by mariusalexander** [comment]
I could reproduce the error and implemented a fix
