### ISSUE TITLE
Restore/recenter the position and zoom factor of the view when switching between scenes

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/intelligraph-module#213]
Sorry for the long title.

If you go to a subgraph move in the graph and then go back it would be helpful to start the view at the sub-graph node

**Comment by mariusalexander** [comment]
Issue: The view only centers the scene when opening a subgraph. When switching to the parent graph the view position and zoom factor is not recentered/restored which may result the view being off center
