### ISSUE TITLE
Adding an input/output port to a dynamic node that is not allowed should fail

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/intelligraph-module#99]
In GitLab by @mariusalexander on May 27, 2024, 06:57

## Summary

For Dynamic nodes that only accept input, output or no dynamic ports at all adding an input/output port actually succeeds instead of returning an invalid PortId.

```cpp
    intelli::GroupInputProvider* input = /*...*/;
    input->addInPort(intelli::typeId<intelli::DoubleData>()); // this succeeds but causes haywire in the dynamic node
```
## What is the expected correct behavior?

The port-id should be invalid and the port should not be added

**Comment by mariusalexander** [comment]
If one should not add an input or output port to a dynamic node with the option `DynamicInputOnly` or `DynamicOutputOnly` one can override the protected `insertPort` function to exit if necessary. I think this is the best solution.
